# frozen_string_literal: true

# Helper module for Forms generated by the EzOnRails::EzForm generator.
module EzOnRails::EzFormHelper
  # Renders a container tag holding the attribute of the current form object having the
  # attribute_key and the specified attribute_render_info. The specified block is yielded
  # into the container.
  def render_attribute_container_form(_data, _attribute_key, _attribute_render_info, &)
    tag.div(class: 'mb-3', &)
  end

  # Default render function for an ezform active model attribute with
  # the attribute render information.
  # The data is expected to be the form builder.
  def render_default_form(data, attribute_key, attribute_render_info)
    render_attribute :model_form, data, attribute_key, attribute_render_info
  end
end
